CC      := $(CROSS_COMPILE)gcc
target = 

default:
	@echo "compile done......"

install:
	cp -avf *.sh $(target) $(TOOL_BIN_DIR)
	@echo "install done......"

clean:
	rm -rf $(target)
	@echo "clean done......"
