#include ../../conf/env.cfg
INCLUDEDIR 	:= 
SHAREDFLAG 	:= 
CC:=$(CROSS_COMPILE)gcc
CXX:=$(CROSS_COMPILE)g++
CFLAGS=-g -o

All:
	$(CC) -g -o hashline2 hashline2.c

install:
	@echo "do nothing ......."

clean:
	rm -rf hashline2
