#!/usr/bin/expect -f 
#   Copyright 2005, 2007-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */
source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc
global GDBPROMPT
global gdb_prompt
global target_ip
global target_prompt
global inferior_exited_re

spawn ssh root@$target_ip
expect {
    -timeout 2
    -re "$target_prompt*" {}
timeout {
        send_user "\n*****error: ssh root@$target_ip failed*****\n"
        set GRET [expr $GRET + 1]
        exit 1
    }
}

proc cmd_exp {args} {
    global GRET;
    set command [lindex $args 0]
    set retkey [lindex $args 1]

    send "$command\n"
    expect {
        -timeout 30
        -re "$retkey" {
            return 1
        }
        timeout {
            send_user "\n*****error: $command string key mismatch $retkey *****\n"
            set GRET [expr $GRET + 1]
            return 0
        }
    }
	return 1
}

set target_prompt "/tmp/for_gdb_test/base_test"
cmd_exp "cd $target_prompt" "$target_prompt*"

#if $tracelevel then {
#	strace $tracelevel
#	}

#if { [is_remote target] || ![isnative] } then {
#    continue
#}

# Until "set follow-fork-mode" and "catch fork" are implemented on
# other targets...
#
#if {![istarget "*-*-linux*"]} then {
#    continue
#}


set testfile "checkpoint"
set srcfile ${testfile}.c
set binfile ${testfile}

#if  { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" executable {debug}] != "" } {
#     untested checkpoint.exp
#     return -1
#}

# Start with a fresh gdb

#gdb_exit
#gdb_start
#gdb_reinitialize_dir $srcdir/$subdir
#gdb_load ${binfile}

cmd_exp "'$GDB_TOOL_DIR'gdb $binfile" "$gdb_prompt"

#
# This tests gdb checkpoint and restart.
#

#remote_download host ${srcdir}/${subdir}/pi.txt pi.txt

gdb_test_no_output "set height 500"
runto_main
set break1_loc [gdb_get_line_number "breakpoint 1"]
set break2_loc [gdb_get_line_number "breakpoint 2"]
set break3_loc [gdb_get_line_number "breakpoint 3"]
set break4_loc [gdb_get_line_number "breakpoint 4"]

gdb_breakpoint $break1_loc
cmd_exp "continue" "breakpoint 1.*" "break1 start"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 two"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 three"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 four" 

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 five"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 six"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 seven"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 eight"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 nine"

cmd_exp "checkpoint" ".*" ""
cmd_exp "continue 10" "breakpoint 1.*" "break1 ten"

cmd_exp "checkpoint" ".*" ""

cmd_exp "info checkpoints" \
    " 10 .* 9 .* 8 .* 7 .* 6 .* 5 .* 4 .* 3 .* 2 .* 1 .*" \
    "info checkpoints one"

delete_breakpoints
gdb_breakpoint $break2_loc
cmd_exp "continue" "breakpoint 2.*" "break2 one"

cmd_exp "restart 1" "Switching to .*breakpoint 1.*" "restart 1 one"
cmd_exp "print i" " = 78" "verify i 1 one"
cmd_exp "step" "if .c == EOF.*" "step in 1 one"
cmd_exp "print lines" " = 1.*" "verify lines 1 one"

cmd_exp "restart 2" "Switching to .*breakpoint 1.*" "restart 2 one"
cmd_exp "step" "if .c == EOF.*" "step in 2 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 2 one"
cmd_exp "print lines" " = 11.*" "verify lines 2 one"

cmd_exp "restart 3" "Switching to .*breakpoint 1.*" "restart 3 one"
cmd_exp "step" "if .c == EOF.*" "step in 3 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 3 one"
cmd_exp "print lines" " = 21.*" "verify lines 3 one"

cmd_exp "restart 4" "Switching to .*breakpoint 1.*" "restart 4 one"
cmd_exp "step" "if .c == EOF.*" "step in 4 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 4 one"
cmd_exp "print lines" " = 31.*" "verify lines 4 one"

cmd_exp "restart 5" "Switching to .*breakpoint 1.*" "restart 5 one"
cmd_exp "step" "if .c == EOF.*" "step in 5 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 5 one"
cmd_exp "print lines" " = 41.*" "verify lines 5 one"

cmd_exp "restart 6" "Switching to .*breakpoint 1.*" "restart 6 one"
cmd_exp "step" "if .c == EOF.*" "step in 6 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 6 one"
cmd_exp "print lines" " = 51.*" "verify lines 6 one"

cmd_exp "restart 7" "Switching to .*breakpoint 1.*" "restart 7 one"
cmd_exp "step" "if .c == EOF.*" "step in 7 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 7 one"
cmd_exp "print lines" " = 61.*" "verify lines 7 one"

cmd_exp "restart 8" "Switching to .*breakpoint 1.*" "restart 8 one"
cmd_exp "step" "if .c == EOF.*" "step in 8 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 8 one"
cmd_exp "print lines" " = 71.*" "verify lines 8 one"

cmd_exp "restart 9" "Switching to .*breakpoint 1.*" "restart 9 one"
cmd_exp "step" "if .c == EOF.*" "step in 9 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 9 one"
cmd_exp "print lines" " = 81.*" "verify lines 9 one"

cmd_exp "restart 10" "Switching to .*breakpoint 1.*" "restart 10 one"
cmd_exp "step" "if .c == EOF.*" "step in 10 one"
cmd_exp "print i + 1 == lines * 79" " = 1" "verify i 10 one"
cmd_exp "print lines" " = 91.*" "verify lines 10 one"

#
# Now let the files be closed by the original process, 
# and diff them.

cmd_exp "restart 0" "Switching to .*breakpoint 2.*" "restart 0 one"
gdb_breakpoint $break3_loc
cmd_exp "continue" "breakpoint 3.*" "break3 one"

cmd_exp "shell diff -s pi.txt copy1.txt" \
    "Files pi.txt and copy1.txt are identical.*" \
    "Diff input and output one"

#
# And now run from various checkpoints, allowing 
# various amounts of input and output.
#

gdb_breakpoint $break1_loc

cmd_exp "restart 1" "Switching to .*c == EOF.*" "restart 1 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 100" "breakpoint 1.*" "breakpoint 1 1 one"
cmd_exp "step" "if .c == EOF.*" "step in 1 two"
cmd_exp "print lines" " = 102.*" "verify lines 1 two"

cmd_exp "restart 2" "Switching to .*c == EOF.*" "restart 2 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 100" "breakpoint 1.*" "breakpoint 1 2 one"
cmd_exp "step" "if .c == EOF.*" "step in 2 two"
cmd_exp "print lines" " = 112.*" "verify lines 2 two"

cmd_exp "restart 3" "Switching to .*c == EOF.*" "restart 3 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 500" "breakpoint 1.*" "breakpoint 1 3 one"
cmd_exp "step" "if .c == EOF.*" "step in 3 two"
cmd_exp "print lines" " = 522.*" "verify lines 3 two"

cmd_exp "restart 4" "Switching to .*c == EOF.*" "restart 4 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 500" "breakpoint 1.*" "breakpoint 1 4 one"
cmd_exp "step" "if .c == EOF.*" "step in 4 two"
cmd_exp "print lines" " = 532.*" "verify lines 4 two"

cmd_exp "restart 5" "Switching to .*c == EOF.*" "restart 5 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 1000" "breakpoint 1.*" "breakpoint 1 5 one"
cmd_exp "step" "if .c == EOF.*" "step in 5 two"
cmd_exp "print lines" " = 1042.*" "verify lines 5 two"

cmd_exp "restart 6" "Switching to .*c == EOF.*" "restart 6 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 1000" "breakpoint 1.*" "breakpoint 1 6 one"
cmd_exp "step" "if .c == EOF.*" "step in 6 two"
cmd_exp "print lines" " = 1052.*" "verify lines 5 two"

cmd_exp "restart 7" "Switching to .*c == EOF.*" "restart 7 two"
cmd_exp "continue" ".*" ""
cmd_exp "continue 1100" "breakpoint 1.*" "breakpoint 1 7 one"
cmd_exp "step" "if .c == EOF.*" "step in 7 two"
cmd_exp "print lines" " = 1162.*" "verify lines 7 two"

cmd_exp "shell diff -s pi.txt copy1.txt" \
    "Files pi.txt and copy1.txt are identical.*" \
    "Diff input and output two"

# 
# OK, now allow the original program to delete the output file, 
# and verify that the checkpoints can still write to it.
# 

cmd_exp "restart 0" "Switching to .*breakpoint 3.*" "restart 0 one"
gdb_breakpoint $break4_loc
cmd_exp "continue" "breakpoint 4.*" "break4 one"

cmd_exp "shell diff pi.txt copy1.txt" \
    "No such file or directory" \
    "delete copy1"

delete_breakpoints
gdb_breakpoint $break2_loc

cmd_exp "restart 1" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 1 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 1"

cmd_exp "restart 2" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 2 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 2"

cmd_exp "restart 3" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 3 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 3"

cmd_exp "restart 4" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 4 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 4"

cmd_exp "restart 5" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 5 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 5"

cmd_exp "restart 6" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 6 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 6"

cmd_exp "restart 7" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 7 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 7"

cmd_exp "restart 8" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 8 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 8"

cmd_exp "restart 9" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 9 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 9"

cmd_exp "restart 10" "if .c == EOF.*" "restart 1 three"
cmd_exp "continue" "breakpoint 2.*" "break2 10 one"
cmd_exp "print ftell (out) > 100000" " = 1.*" "outfile still open 10"

#
# Now confirm that if one fork exits, we automatically switch to another one.
#

delete_breakpoints
cmd_exp "continue" \
    "Deleting copy.*$inferior_exited_re normally.*Switching to.*" \
    "Exit, dropped into next fork one"

cmd_exp "continue" \
    "Deleting copy.*$inferior_exited_re normally.*Switching to.*" \
    "Exit, dropped into next fork two"

cmd_exp "continue" \
    "Deleting copy.*$inferior_exited_re normally.*Switching to.*" \
    "Exit, dropped into next fork three"

cmd_exp "continue" \
    "Deleting copy.*$inferior_exited_re normally.*Switching to.*" \
    "Exit, dropped into next fork four"

cmd_exp "continue" \
    "Deleting copy.*$inferior_exited_re normally.*Switching to.*" \
    "Exit, dropped into next fork five"

#
# There should be still at least five forks left
# 

cmd_exp "info checkpoints" " 5 .* 4 .* 3 .* 2 .* 1 .*" \
    "info checkpoints two"

#
# Kill should now terminate all of them.
#

cmd_exp "kill" "Kill the program being debugged.*y or n. $" 
cmd_exp "y" "$gdb_prompt"
#"" "kill all one" \

# 
# and confirm that all are gone
#

cmd_exp "restart 0" "Not found.*" "no more checkpoint 0"
cmd_exp "restart 1" "Not found.*" "no more checkpoint 1"
cmd_exp "restart 2" "Not found.*" "no more checkpoint 2"
cmd_exp "restart 3" "Not found.*" "no more checkpoint 3"
cmd_exp "restart 4" "Not found.*" "no more checkpoint 4"
cmd_exp "restart 5" "Not found.*" "no more checkpoint 5"
cmd_exp "restart 6" "Not found.*" "no more checkpoint 6"
cmd_exp "restart 7" "Not found.*" "no more checkpoint 7"
cmd_exp "restart 8" "Not found.*" "no more checkpoint 8"
cmd_exp "restart 9" "Not found.*" "no more checkpoint 9"
cmd_exp "restart 10" "Not found.*" "no more checkpoint 10"


#
# Now let's try setting a large number of checkpoints (>600)
#

gdb_exit
#gdb_start
#gdb_reinitialize_dir $srcdir/$subdir
#gdb_load ${binfile}
cmd_exp "'$GDB_TOOL_DIR'gdb $binfile" "$gdb_prompt"

runto_main
gdb_breakpoint $break1_loc

cmd_exp "commands\nsilent\nif (lines % 2)\ncheckpoint\nend\n  continue\nend" \
    "" \
    "set checkpoint breakpoint"

#verbose "Timeout now $timeout sec."

gdb_breakpoint $break2_loc
send "continue\n"
expect {
    -timeout 300
    -re "reakpoint 3.*$gdb_prompt" {
    }
    timeout {
        send_user "timeout 382"
        set GRET [expr $GRET + 1]
    }
}    
set count 0
set msg "info checkpoints with at least 600 checkpoints"
send "info checkpoints\n"
expect {
    -re "  $decimal process \[^\r\]*\r\n" {
	incr count
	exp_continue
    }
    -re "$gdb_prompt" {
	if { $count >= 600 } {
#	    pass $msg
	} else {
	    send_user "fail $msg"
        set GRET [expr $GRET + 1]
	}
    }
    -re "return" {
        send "\n"
        exp_continue
    }
}    

#
# OK, kill 'em all...
#

cmd_exp "kill" "" "kill all one with many checkpoints" \
    "Kill the program being debugged.*y or n. $" "y"

# Restore old timeout
#verbose "Timeout now $timeout sec."

#
# Finished: cleanup
#

exit $GRET

interact
