#!/usr/bin/expect -f

#   Copyright 1998-1999, 2007-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.  */
source ../lib/gdb_proc.exp
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc             
global GDBPROMPT
global target_ip 
global  target_prompt 

spawn ssh root@$target_ip

expect {
    -timeout 2
        -re "$target_prompt*" {
#            send_user "string key match while ssh $target_ip"
        }   
    timeout {
#        send_user "Please check string key while ssh $target_ip"
            set GRET [expr $GRET + 1]
    }   
}

gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt*"
gdb_test "'$GDB_TOOL_DIR'gdb cursal" "$GDBPROMPT"
gdb_test "set listsize 1" "$GDBPROMPT"

# initial sal should be first statement in main
gdb_test "list" \
    "v0 = 0;" \
    "list before run"

gdb_test "b main" "$GDBPROMPT"
gdb_test "r" "int v0 = 0;.*$GDBPROMPT"
gdb_test "list" \
    "v0 = 0;" \
    "list in main"

gdb_test "b func2" "$GDBPROMPT"
gdb_test "c" "int v2 = 2;.*$GDBPROMPT"

gdb_test "list" \
    "v2 = 2;" \
    "list in func2"

# make sure backtrace doesn't change current source location.
gdb_test "backtrace" \
    ".*"
gdb_test "list -1" \
    "v2 = 2;" \
    "list after backtrace"

# check the window
gdb_test "set listsize 3" "$GDBPROMPT"

gdb_test "r" "\\(y or n\\)"
gdb_test "y" "int v0 = 0;.*$GDBPROMPT"

gdb_test "list" \
    "func1 \\(\\);" \
    "list size 3"

exit $GRET

interact
