#!/usr/bin/expect -f

# This testcase is part of GDB, the GNU debugger.

# Copyright 2010-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc
global GDBPROMPT
global gdb_prompt
global target_ip
global target_prompt
global inferior_exited_re

spawn ssh root@$target_ip
expect {
	-timeout 2
	-re "$target_prompt*" {}
	timeout {
		send_user "\n*****error: ssh root@$target_ip failed*****\n"
		exit 1
	}
}

set target_prompt "/tmp/for_gdb_test/base_test"
gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt"

# Test GDB bug report 11530.
# This is a problem related unnamed unions.

#if $tracelevel then {
#	strace $tracelevel
#}

set testfile "gdb11530"
#set binfile ${testfile}${EXEEXT}

# Unnamed union is a GNU extension, thus we restrict the test
# to gcc compiler.

#if [get_compiler_info ${binfile}] {
#    return -1;
#}

#if { ![test_compiler_info gcc*] } {
#    return 0;
#}

#if { [prepare_for_testing $testfile.exp $testfile $testfile.c {debug}] } {
#    return -1;
#}

gdb_test "'$GDB_TOOL_DIR'gdb $testfile" "$GDBPROMPT*"

if { ![runto main] } then {
    send_user "fail run to main"
    exit -1
}

gdb_test "print a.i" " = 0"
gdb_test "print sizeof (a.i)" " = \[0-9\]+"
gdb_test "print sizeof (a.i) == sizeof (int)" " = 1"

exit $GRET
interact

