#!/usr/bin/expect -f

# Copyright 2009-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc
global GDBPROMPT
global gdb_prompt
global target_ip
global target_prompt
global inferior_exited_re

spawn ssh root@$target_ip
expect {
	-timeout 2
	-re "$target_prompt*" {}
	timeout {
		send_user "\n*****error: ssh root@$target_ip failed*****\n"
		exit 1
	}
}

set target_prompt "/tmp/for_gdb_test/base_test"
gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt"

#if {[skip_hw_breakpoint_tests]} {
#    return 0
#}

set testfile hbreak
set srcfile ${testfile}.c
#if { [prepare_for_testing ${test}.exp ${test} ${srcfile}] } {
#    return -1
#}

gdb_test "'$GDB_TOOL_DIR'gdb $testfile" "$GDBPROMPT*"

if ![runto_main] {
    untested ${test}.exp
    return -1
}

set breakline [gdb_get_line_number "break-at-exit"]

gdb_test "hbreak ${srcfile}:${breakline}" \
	 "Hardware assisted breakpoint \[0-9\]+ at 0x\[0-9a-f\]+: file .*${srcfile}, line ${breakline}\\." \
	 "hbreak"

gdb_test "continue" \
	 "Continuing\\.\[ \r\n\]+Breakpoint \[0-9\]+, .*break-at-exit.*" \
	 "continue to break-at-exit after hbreak"

exit $GRET
interact
