#!/usr/bin/expect -f

# Copyright 2007-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc
global GDBPROMPT
global gdb_prompt
global target_ip
global target_prompt
global inferior_exited_re

spawn ssh root@$target_ip
expect {
	-timeout 2
	-re "$target_prompt*" {}
	timeout {
		send_user "\n*****error: ssh root@$target_ip failed*****\n"
		exit 1
	}
}

set target_prompt "/tmp/for_gdb_test/base_test"
gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt"

#if $tracelevel {
#    strace $tracelevel
#}

set testfile "nofield"
set srcfile ${testfile}.c
#set binfile ${objdir}/${subdir}/${testfile}
#if { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" executable {debug}] != "" } {
#    untested "Couldn't compile ${srcfile}"
#    return -1
#}

gdb_test "'$GDB_TOOL_DIR'gdb $testfile" "$GDBPROMPT"

set eol "\[\r\n\]+"
set sp "\[ \t\]*"

#gdb_exit
#gdb_start
#gdb_reinitialize_dir $srcdir/$subdir
#gdb_load ${binfile}

gdb_test "ptype struct not_empty" \
         "type = struct not_empty {$eol${sp}void \\*e;$eol${sp}void \\*u;$eol}" \
         "ptype struct not_empty"

gdb_test "ptype struct empty" \
        "type = struct empty {$eol$sp<no data fields>$eol}" \
         "ptype struct empty"

gdb_test "ptype union empty_union" \
         "type = union empty_union {$eol$sp<no data fields>$eol}" \
         "ptype union empty_union"

exit $GRET
interact
