#!/usr/bin/expect -f

# Copyright 2006-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc
global GDBPROMPT
global gdb_prompt
global target_ip
global target_prompt
global inferior_exited_re

spawn ssh root@$target_ip
expect {
	-timeout 2
	-re "$target_prompt*" {}
	timeout {
		send_user "\n*****error: ssh root@$target_ip failed*****\n"
		exit 1
	}
}

set target_prompt "/tmp/for_gdb_test/base_test"
gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt"

#if $tracelevel then {
#    strace $tracelevel
#}

#
# test running programs
#

set testfile "sepsymtab"
set srcfile ${testfile}.c
#set binfile ${objdir}/${subdir}/${testfile}${EXEEXT}

#if { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" \
#	  executable {debug}] != "" } {
#    untested sepsymtab.exp
#    return -1
#}

#if [gdb_gnu_strip_debug $binfile no-main] {
    # check that you have a recent version of strip and objcopy installed
#    unsupported "cannot produce separate debug info files"
#    return -1
#}

#gdb_exit
#gdb_start
#gdb_reinitialize_dir $srcdir/$subdir
#gdb_load ${binfile}

gdb_test "'$GDB_TOOL_DIR'gdb $testfile" "$GDBPROMPT"


set command "info sym main"
set command_regex [string_to_regexp $command]
send "$command\n" 
    expect {
    -re "$command_regex.*main in section.*$GDBPROMPT" {
	send_user "pass $command"
    }
}

exit $GRET
interact
