#!/usr/bin/expect -f
# This testcase is part of GDB, the GNU debugger.

# Copyright 2008-2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source ../lib/gdb_proc.exp
global target_dir
global GRET;
set GRET 0;
global ARGC;
global GDB_TOOL_DIR
set ARGC $argc             
global GDBPROMPT
global gdb_prompt
global target_ip 
global  target_prompt 

if ![login_board] {
	exit 1
}

spawn ssh root@$target_ip
expect {
    -timeout 2
            -re "$target_prompt*" {}
    timeout {
		send_user "\n*****error: ssh root@$target_ip failed*****\n"
		exit 1
	}
}

set target_prompt "/tmp/for_gdb_test/base_test"
gdb_test "cd /tmp/for_gdb_test/base_test" "$target_prompt"

#if $tracelevel then {
#    strace $tracelevel
#}

#set testfile step-break
#set srcfile ${testfile}.c
#set binfile ${objdir}/${subdir}/${testfile}

#if { [gdb_compile "${srcdir}/${subdir}/${srcfile}" "${binfile}" executable {debug}] != "" } {
#     untested step-break.exp
#     return -1
#}

#gdb_exit
#gdb_start
#gdb_reinitialize_dir $srcdir/$subdir
#gdb_load ${binfile}

#if ![runto_main] then {
#   fail "Can't run to main"
#   return 0
#}
gdb_test "'$GDB_TOOL_DIR'gdb step-break" "$GDBPROMPT"

gdb_test "b main" "$GDBPROMPT"
gdb_test "r" "volatile int i = 1;.*$GDBPROMPT"

set bp_location 28
set srcfile "step-break.c"
gdb_test "break $bp_location" \
    "Breakpoint.*at.* file .*$srcfile, line $bp_location\\." \
    "breakpoint line number"

gdb_test continue "Continuing\\..*Breakpoint \[0-9\]+, main \\(\\) at .*$srcfile:$bp_location.*set breakpoint here.*" \
    "run until breakpoint set at a line number"

gdb_test "next 2" ".*place2.*" "next 2 (1)"
gdb_test "next 2" ".*place3.*" "next 2 (2)"
gdb_test "next 2" ".*place2.*" "next 2 (3)"
gdb_test "next 2" ".*place3.*" "next 2 (4)"
gdb_test "next 2" ".*place2.*" "next 2 (5)"
gdb_test "next 2" ".*place3.*" "next 2 (6)"

exit $GRET
interact
